module.exports = [
  "IIT Madras",
  "IIT Delhi",
  "IIT Kharagpur",
  "IIT Kanpur",
  "IIT Bombay",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT (BHU) Varanasi",
  "IIT Bhubaneshwar",
  "IIT Gandhinagar",
  "IIT Hyderabad",
  "IIT Jodhpur",
  "IIT Patna",
  "IIT Ropar",
  "IIT Indore",
  "IIT Mandi",
  "IIT Palakkad",
  "IIT Tirupati",
  "IIT Dhanbad",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Jammu",
  "IIT Dharwad"
];
